version: "3.9"

services:
  build:
    image: node:18.16.0-alpine
    command:
      - sh
      - -c
      - |
        npm install
        npm run build
    working_dir: /app
    volumes:
      - .:/app
      - build:/app/dist
      - node_cache:/app/node_modules
  clean:
    image: busybox
    command:
      - sh
      - -c
      - |
        rm -rf dist
        rm -rf node_modules
    working_dir: /app
    volumes:
      - .:/app
      - build:/app/dist
      - node_cache:/app/node_modules
  k6:
    image: grafana/k6
    environment:
      - TEST=$TEST
    # command: run --log-output=loki=http://localhost:3100/loki/api/v1/push,label.qa=k6 /dist/$TEST.js
    # command: run --out influxdb=http://localhost:8086/k6 --log-output=loki=http://localhost:3100/loki/api/v1/push,label.qa=k6 /dist/$TEST.js 
    command: run /dist/$TEST.js
    volumes:
      - build:/dist
    depends_on:
      - build
    network_mode: host

volumes:
  build:
  node_cache:
